name: appi
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  path_provider: ^2.0.9
  location: ^4.3.0
  google_sign_in: ^5.2.4
  firebase_auth: ^3.3.11
  google_maps_flutter: ^2.1.10
  flutter_credit_card: ^3.0.3
  firebase_remote_config: ^2.0.17
  shared_preferences: ^2.0.15
  http: ^0.13.5
  google_polyline_algorithm: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/
