// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1kp5uRQo_8S-j3ONjPul21TDGoXh3Tpo',
    appId: '1:675729663493:web:e50042176c4ceac7675e6c',
    messagingSenderId: '675729663493',
    projectId: 'apiipp',
    authDomain: 'apiipp.firebaseapp.com',
    storageBucket: 'apiipp.appspot.com',
    measurementId: 'G-J3PB8W3Z5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3QgZX6gK_p6NbG3EP4diLkk4S1r8FWUA',
    appId: '1:675729663493:android:8e188cb1f6e0a028675e6c',
    messagingSenderId: '675729663493',
    projectId: 'apiipp',
    storageBucket: 'apiipp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwJa8z_hlcYflNDo5LlPZeSdD62fAFi-A',
    appId: '1:675729663493:ios:b8b824c4591f6ad2675e6c',
    messagingSenderId: '675729663493',
    projectId: 'apiipp',
    storageBucket: 'apiipp.appspot.com',
    iosClientId: '675729663493-942bhtd2s5e56vjeclbc62ekf2mt4mec.apps.googleusercontent.com',
    iosBundleId: 'com.example.appi',
  );
}
